server:
    port: 9000
spring:
    application:
        name: SseNotification
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: final123!@#
        url: jdbc:mysql://db-oeqm8-kr.vpc-pub-cdb.ntruss.com:3306/final?serverTimezone=Asia/Seoul
        username: bitcamp
        hikari:
            maximum-pool-size: 80  # 최대 연결 수
            minimum-idle: 40  # 유휴 상태에서도 유지할 연결 수
            idle-timeout: 30000    # 유휴 상태에서 커넥션을 유지하는 시간 (밀리초)
            max-lifetime: 1800000  # 커넥션이 최대로 유지되는 시간 (밀리초)
            connection-timeout: 30000  # 커넥션을 얻기 위해 대기하는 최대 시간 (밀리초)
    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MySQLDialect
        generate-ddl: true
        hibernate:
            ddl-auto: update
        show-sql: true
spring:
  web:
    cors:
      allow-credentials: true
      allowed-origins: "https://api.icebuckwheat.kro.kr"
      allowed-methods: 
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
